// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca2.Models;

public partial class Autor
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Bibliografia { get; set; }

    public DateOnly? DataNascimento { get; set; }

    public DateOnly? DataMorte { get; set; }

    public virtual ICollection<LivroAutor> LivroAutors { get; set; } = new List<LivroAutor>();
}