// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Biblioteca2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Biblioteca2.Models
{
    public partial class Biblioteca2Context
    {
        private IBiblioteca2ContextProcedures _procedures;

        public virtual IBiblioteca2ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Biblioteca2ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBiblioteca2ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Biblioteca2ContextProcedures : IBiblioteca2ContextProcedures
    {
        private readonly Biblioteca2Context _context;

        public Biblioteca2ContextProcedures(Biblioteca2Context context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_Utilizadores_Sexo_FaixaEtariaResult>> SP_Utilizadores_Sexo_FaixaEtariaAsync(OutputParameter<int?> executionTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterExecutionTime = new SqlParameter
            {
                ParameterName = "ExecutionTime",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = executionTime?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterExecutionTime,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_Utilizadores_Sexo_FaixaEtariaResult>("EXEC @returnValue = [dbo].[SP_Utilizadores_Sexo_FaixaEtaria] @ExecutionTime = @ExecutionTime OUTPUT", sqlParameters, cancellationToken);

            executionTime?.SetValue(parameterExecutionTime.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
