// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca2.Models;

public partial class Categorium
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<Livro> Livros { get; set; } = new List<Livro>();
}