// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca2.Models;

public partial class EmprestimoLivro
{
    public int EmprestimoId { get; set; }

    public int LivroId { get; set; }

    public int Quantidade { get; set; }

    public virtual Emprestimo Emprestimo { get; set; }

    public virtual Livro Livro { get; set; }
}