// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca2.Models;

public partial class Emprestimo
{
    public int Id { get; set; }

    public int UtilizadorId { get; set; }

    public DateOnly DataEmprestimo { get; set; }

    public DateOnly? DataDevolucaoPrevista { get; set; }

    public DateOnly? DataDevolucaoReal { get; set; }

    public int EstadoId { get; set; }

    public virtual ICollection<EmprestimoLivro> EmprestimoLivros { get; set; } = new List<EmprestimoLivro>();

    public virtual EmprestimoEstado Estado { get; set; }
}