// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Biblioteca2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Biblioteca2.Models
{
    public partial interface IBiblioteca2ContextProcedures
    {
        Task<List<SP_Utilizadores_Sexo_FaixaEtariaResult>> SP_Utilizadores_Sexo_FaixaEtariaAsync(OutputParameter<int?> executionTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
