// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Biblioteca2.Models;

public partial class Livro
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public int AnoPublicacao { get; set; }

    public int EditoraId { get; set; }

    public int AnoEdicao { get; set; }

    public int? Exemplares { get; set; }

    public virtual Editora Editora { get; set; }

    public virtual ICollection<EmprestimoLivro> EmprestimoLivros { get; set; } = new List<EmprestimoLivro>();

    public virtual ICollection<LivroAutor> LivroAutors { get; set; } = new List<LivroAutor>();

    public virtual ICollection<Categorium> Categoria { get; set; } = new List<Categorium>();
}