// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Biblioteca2.Models
{
    public partial class SP_Utilizadores_Sexo_FaixaEtariaResult
    {
        public string Sexo { get; set; }
        [StringLength(5)]
        public string FaixaEtaria { get; set; }
        public int? Total { get; set; }
    }
}
